apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-sd15-deployment
  labels:
    app: stable-diffusion-sd15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-sd15
  template:
    metadata:
      labels:
        app: stable-diffusion-sd15
    spec:
      containers:
      - name: stable-diffusion-webui
        #imagePullPolicy: Always
        image:  us-central1-docker.pkg.dev/winter-inquiry-377308/stable-diffusion/sd-with-api:upscaler
        resources:
          limits:
            cpu: 4000m
            memory: 24Gi
            nvidia.com/gpu: 1
        ports:
          - containerPort: 7860
        readinessProbe:
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 7860
          initialDelaySeconds: 5
          periodSeconds: 5
