apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-invokeai-service
  labels:
    app: stable-diffusion-invokeai
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: stable-diffusion-invokeai
  type: LoadBalancer